services:
  my-university-api-gateway:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-Development}
      - JWT_KEY=${JWT_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}